export const MAX_HP = 100;
export const BASE_DAMAGE = 25;
export const MAJOR_DAMAGE = 15;
export const MINOR_DAMAGE = 5;
export const PUZZLE_DEADLINE_MS = 8000;
export const ATTACK_COOLDOWN_MS = 15000;

export const XP_ERROR_MESSAGES = [
  "SYSTEM SHUTDOWN :: INITIATED BY EXTERNAL AGENT",
  "CRITICAL ERROR :: UNAUTHORIZED MEMORY ACCESS",
  "SECURITY BREACH :: MALICIOUS PAYLOAD DETECTED",
];
